name: Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api_services/requirements.txt
          pip install setuptools wheel twine

      - name: List api_services directory
        run: |
          ls -la api_services

      - name: Run tests
        run: |
          PYTHONPATH=api_services pytest api_services/tests
      
      - name: Build package
        run: |
          cd api_services
          python setup.py sdist bdist_wheel
          ls -la dist

      - name: Publish to PyPI
        run: |
          ls -la api_services/dist  # List contents of the dist folders
          twine upload api_services/dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
